# Generated by Django 4.2.7 on 2024-09-30 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AidTogether', '0004_reliefcampprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationprofile',
            name='org_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profileimages/'),
            preserve_default=False,
        ),
    ]
