# Generated by Django 4.2.7 on 2024-10-04 12:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('AidTogether', '0005_organisationprofile_org_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='reliefcampprofile',
            name='camp_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profileimages/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='vol_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profileimages/'),
            preserve_default=False,
        ),
    ]
