# Generated by Django 4.2.7 on 2024-10-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AidTogether', '0006_reliefcampprofile_camp_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationprofile',
            name='org_image',
            field=models.ImageField(upload_to='media/profileimages/'),
        ),
    ]
