# Generated by Django 5.1 on 2024-10-30 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AidTogether', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=255)),
                ('requester_phone', models.CharField(max_length=15)),
                ('resource_type', models.CharField(choices=[('FOOD', 'Food'), ('MEDICAL_SUPPLIES', 'Medical Supplies'), ('VOLUNTEERS', 'Volunteers'), ('EQUIPMENT', 'Equipment'), ('SHELTER', 'Shelter')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('request_details', models.TextField()),
                ('delivery_address', models.TextField()),
                ('requested_by_date', models.DateField()),
                ('urgency_level', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('24_HOURS', 'Next 24 Hours'), ('WEEK', 'Within a Week')], max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Denied', 'Denied')], default='Pending', max_length=20)),
                ('camp', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource_requests', to='AidTogether.reliefcampprofile')),
            ],
        ),
    ]
